pipeline {
	agent any
	// agent {
	// 	docker {
	// 		image 'gradle:jre8'
	// 	}
	//}
	stages{
		stage('Build') {
			steps {
				echo "Build"
				echo "$PATH"
				echo "BUILD NUMBER - $env.BUILD_NUMBER"
				echo "BUILD_ID - $env.BUILD_ID"
				echo "JOB NAME - env.JOB_NAME"
				echo "$env.BUILD_TAG"
				echo "$env.BUILD_URL"
				echo "Integration test"
			}
		}

		stage('Test') {
			steps {
				echo "Test"
			}
		}

		stage('Integration Test') {
			steps {
				echo "Integration Test"
			} 
		}
	}

post {
	always {
		echo 'I am awesome'
	}
	success {
		echo 'I run mostly to succeed'
	}
	failure {
		echo 'I run when you fail'
	}
	cleanup {
		echo 'This is a cleanup process'
	}
	changed {
		echo 'Its changed'
	}
}
}
