pipeline {
	//agent any
	agent {
		docker {
			image 'ant:latest'
		}
	}
	stages{
		stage('Build') {
			steps {
				echo "Build"
				
				echo "Integration test"
			}
		}

		stage('Test') {
			steps {
				echo "Test"
			}
		}

		stage('Integration Test') {
			steps {
				echo "Integration Test"
			} 
		}
	}

post {
	always {
		echo 'I am awesome'
	}
	success {
		echo 'I run mostly to succeed'
	}
	failure {
		echo 'I run when you fail'
	}
	cleanup {
		echo 'This is a cleanup process'
	}
	changed {
		echo 'Its changed'
	}
}
}