pipeline {
	agent any
	stages{
		stage('Build') {
			steps {
				echo "Build"
				
				echo "Integration test"
			}
		}

		stage('Test') {
			steps {
				echo "Test"
			}
		}

		stage('Integration Test') {
			steps {
				echo "Integration Test"
			}
		}
	}
}